-- ═══════════════════════════════════════════════════════════
-- PARKD — Drop All Tables (correct dependency order)
-- Run in SQL*Plus: @"...\database\drop_all.sql"
-- ═══════════════════════════════════════════════════════════

DROP TABLE BILL_CALCULATION CASCADE CONSTRAINTS;
DROP TABLE BILL CASCADE CONSTRAINTS;
DROP TABLE QUEUE CASCADE CONSTRAINTS;
DROP TABLE PARKING_RECORD CASCADE CONSTRAINTS;
DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE USER_PLAN CASCADE CONSTRAINTS;
DROP TABLE OFFER CASCADE CONSTRAINTS;
DROP TABLE PARKING_SLOT CASCADE CONSTRAINTS;
DROP TABLE PARKING_ZONE CASCADE CONSTRAINTS;
DROP TABLE ZONE_RATE CASCADE CONSTRAINTS;
DROP TABLE FACILITY_LOCATION CASCADE CONSTRAINTS;
DROP TABLE VEHICLE CASCADE CONSTRAINTS;
DROP TABLE PLATINUM CASCADE CONSTRAINTS;
DROP TABLE GOLD CASCADE CONSTRAINTS;
DROP TABLE GENERAL CASCADE CONSTRAINTS;
DROP TABLE PLAN_DETAILS CASCADE CONSTRAINTS;
DROP TABLE PLAN CASCADE CONSTRAINTS;
DROP TABLE LOCAL_ADMIN CASCADE CONSTRAINTS;
DROP TABLE SUPER_ADMIN CASCADE CONSTRAINTS;
DROP TABLE FACILITY CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE USER_TABLE CASCADE CONSTRAINTS;

BEGIN
  FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name LIKE 'SEQ_%') LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

COMMIT;
PROMPT All Parkd objects dropped.
